appName: Quarantine Server
server:
  applicationConnectors:
    - type: http
      port: 8080
database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:quarantine.db
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: logs/application.log
      queueSize: 2048
      archivedLogFilenamePattern: logs/archive/application_%d.zip
      archivedFileCount: 30
      bufferSize: 256KB